language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
      - python: "nightly"

install:
  - sudo apt-get -qq update
  - sudo apt-get -y install pandoc
  - python -m pip install -U pip
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - pip install -e .
